### ISSUE TITLE
[Feature] Make URLs into links

### ISSUE THREAD

**Issue by lowcrawler** [dcholth/nothic-bugs#16]
In notes/topics/etc a pasted URL stays as text and isn't clickable.  This hurts ability to just link to a reference during actual game-play and effectively requires me to copy-and-paste everything... which has it's own set of negatives.

**Comment by dcholth** [comment]
I don't understand.  Where?

**Comment by lowcrawler** [comment]
In notes, when I type in a URL... it's not 'clickable' as a link....
