### ISSUE TITLE
[Feature] Allow a 'shift+enter' to line break

### ISSUE THREAD

**Issue by Thatrandomguy199** [dcholth/nothic-bugs#2]
I personally think it would be a great advantage to be able to create sort of lists all in one note. For example, if I wanted to write:
[Player] finds:
-item
-potion
-weapon
-etc...
I would currently have to create 5 separate notes, or place them in a line, which is difficult to read for longer lists and can get confusing.
Other than this, have encountered no bugs so far and it seems like a very useful tool and asset for my campaign starting this Saturday.
Cheers, I appreciate all the work you're doing,
R

**Comment by dcholth** [comment]
This is definitely on the road map and a very requested feature.  I didn't build the initial note taking part to support it, so it will require a fairly big revamp of how I parse the note text.

**Comment by dcholth** [comment]
You can now shift enter to create new lines
