### ISSUE TITLE
Cannot Verify Account

### ISSUE THREAD

**Issue by coaserve** [dcholth/nothic-bugs#28]
I can log onto Nothic, but my dashboard tells me a verification email has been sent, which I've never received (not in junk or any other folder), and the button to send a new one doesn't do anything but change colors when it's pressed. This has been the case for over a week. As an aside, the verification message says to contact support if it doesn't go through in 30 minutes, but there is no contact information available for support on the Nothic site. I've assumed that "report bug" is implied, despite the fact that the "contact support" could easily be changed to "report bug" if that is the desired course of action here. If not, do you have an email for support?

**Comment by dcholth** [comment]
Thanks for reaching out. I do need to correct that messaging. Can you email ##### and include the email address you registered with and I'll get it cleared up ASAP

**Comment by coaserve** [comment]
I will say that the support is much faster than any other support on the
planet, so maybe it does deserve a name that's a step or three above! My
email is #########. Thanks, Dan. I appreciate your help!
- Jacob

**Comment by dcholth** [comment]
Try logging in again.  I think I have an issue in the verification e-mail process, but I went ahead and marked your account as verified.  Let me know if this has fixed the issue.

**Comment by coaserve** [comment]
Boo-yah! Works great. Thank you so much!
