### ISSUE TITLE
[Feature] Suggested Tags in Alphabetical Order

### ISSUE THREAD

**Issue by Locket-Key** [dcholth/nothic-bugs#38]
This one is huge for me. I'm having a hard time sorting through our chronologically tagged session notes when I try to tag them. Each one starts with "21" but the suggestions aren't presented in any particular order I can discern. If they all displayed chronologically, that would save my life here.

**Comment by dcholth** [comment]
Can you post a screen shot?

**Comment by dcholth** [comment]
Can you add a screen shot? @Locket-Key

**Comment by Locket-Key** [comment]
<img width="1645" alt="Screen Shot 2021-06-13 at 4 58 33 PM 1" src="https://user-images.githubusercontent.com/85763791/121821723-c349f080-cc68-11eb-849f-d77f5f773a23.png">

**Comment by Locket-Key** [comment]
The order here is pretty random, so it's hard for me to find the session entries I'm looking for when tagging specific wiki articles.
