### ISSUE TITLE
[Feature] Dropdown Menus Default to Close

### ISSUE THREAD

**Issue by Locket-Key** [dcholth/nothic-bugs#40]
While its nice to have  the dropdowns attempt to remember where you last off, this is very impractical in larger campaigns. We really need either a toggle option that the campaign DM has access to that changes the settings for all players or "close on refresh" to be the default.

**Comment by dcholth** [comment]
'Pinned' will always remain open.

Adding expand and collapse all.

**Comment by dcholth** [comment]
Implemented.
