### ISSUE TITLE
[Feature] Notes that cannot be parent topics

### ISSUE THREAD

**Issue by nospacenoh** [dcholth/nothic-bugs#47]
Currently when we create a note and pick a parent topic the drop down menu displays every topic in the category, not just the parent topics we've designated. Since we have a lot of topics it can be confusing to people trying to figure out what parent topic is appropriate. 

Could we get an update so that we can control which topics are served as options in the parent topic selection dropdown menu?

**Comment by dcholth** [comment]
Implemented.
